---
- name: install packages
  remote_user: ubuntu
  become: true
  hosts: slaves
  tasks:
  - name: updating the packages #similar to apt-get update
    apt:
     update_cache: yes 
  - name: install openjdk8 
    apt:
     name: 
      - openjdk-8-jre-headless
      - awscli
      - nfs-common
     state: present
  - name: If follow=yes, /path/to/file will be overwritten by contents of foo.conf
    copy:
     src: /etc/foo.conf
     dest: /path/to/link  # link to /path/to/file
     follow: yes
  - name: run script
    shell: test.sh >> output.txt
    ...
    