---
- name: install packages
  remote_user: ubuntu
  become: true
  hosts: slaves
  tasks:
  - name: updating the packages #similar to apt-get update
    apt:
     update_cache: yes 
  - name: install openjdk8 
    apt:
     name: 
      - openjdk-8-jre-headless
      - awscli
      - nfs-common
     state: present
  - name: installing specific docker version
     shell:
      cmd: curl https://releases.rancher.com/install-docker/17.03.sh | sh
  - name: Create a directory if it does not exist
     file:
      path: /home/ubuntu/ansible
      state: directory
      mode: '0777'
  - name: If follow=yes, /path/to/file will be overwritten by contents of foo.conf
    copy:
     src: efs.sh
     dest: /home/ubuntu/ansible/efs.sh
     follow: yes
     mode: '1777'
  - name: run script
    shell: efs.sh >> efs_output.txt
...
    
