---
- name: install packages
  remote_user: ubuntu
  become: true
  hosts: slaves
  tasks:
  - name: updating the packages #similar to apt-get update
    apt:
     update_cache: yes 
  - name: install openjdk8 
    apt:
     name: 
      - openjdk-8-jre-headless
      - awscli
      - nfs-common
     state: present
...
    